name: Run Tests

on:
  pull_request:
    branches:
      - main
      - master
      - develop  # Run tests before merging into these branches

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r fast_api/requirements.txt

      - name: Run tests with pytest
        run: |
          cd fast_api
          pytest --disable-warnings --maxfail=1
